"use client";

import { useActionState } from "react";
import { restoreGroupPlace, restoreHiddenContent, restorePlaceCandidate, type PlaceManagementResult } from "@/app/admin/actions";

export type ManagedPlace = { groupPlaceId: string; name: string; address: string; status: "active" | "archived"; archivedAt: string | null; archivedReason: string | null; archivedByName: string | null; opinionCount: number; visitCount: number; photoCount: number };
export type HiddenContent = { id: string; type: "visit" | "photo"; placeName: string; reason: string; hiddenAt: string };
export type ManagedCandidate = { id: string; name: string; status: "pending" | "dismissed"; resolutionType: string | null; resolutionReason: string | null };
const initial: PlaceManagementResult = {};

function RestorePlaceButton({ id }: { id: string }) { const [state, action, pending] = useActionState(restoreGroupPlace, initial); return <form action={action} onSubmit={(event) => { if (!window.confirm("恢复后，这家店会重新出现在发现和地图中。")) event.preventDefault(); }}><input name="group_place_id" type="hidden" value={id} /><button className="secondary-button" disabled={pending}>{pending ? "恢复中…" : "恢复地点"}</button>{state.error && <p className="form-error">{state.error}</p>}</form>; }
function RestoreContentButton({ item }: { item: HiddenContent }) { const [state, action, pending] = useActionState(restoreHiddenContent, initial); return <form action={action}><input name="content_id" type="hidden" value={item.id} /><input name="content_type" type="hidden" value={item.type} /><button className="secondary-button" disabled={pending}>{pending ? "恢复中…" : "恢复显示"}</button>{state.error && <p className="form-error">{state.error}</p>}</form>; }
function RestoreCandidateButton({ id }: { id: string }) { const [state, action, pending] = useActionState(restorePlaceCandidate, initial); return <form action={action}><input name="candidate_id" type="hidden" value={id} /><button className="secondary-button" disabled={pending}>{pending ? "恢复中…" : "恢复候选"}</button>{state.error && <p className="form-error">{state.error}</p>}</form>; }

export function PlaceContentManagement({ activePlaces, archivedPlaces, hiddenContent, pendingCandidates, removedCandidates }: { activePlaces: ManagedPlace[]; archivedPlaces: ManagedPlace[]; hiddenContent: HiddenContent[]; pendingCandidates: ManagedCandidate[]; removedCandidates: ManagedCandidate[] }) {
  return <section className="admin-card place-content-management" id="place-content-management"><h2>地点与内容管理</h2><p>管理地点下架、恢复和已隐藏内容。管理操作不会改写成员的原始观点。</p><div className="management-counts"><span><b>{activePlaces.length}</b>上架中地点</span><span><b>{archivedPlaces.length}</b>已下架地点</span><span><b>{pendingCandidates.length}</b>去试试候选</span><span><b>{hiddenContent.length}</b>已隐藏内容</span></div><h3>上架中</h3>{activePlaces.length ? <ul className="management-list">{activePlaces.map((place) => <li key={place.groupPlaceId}><div><strong>{place.name}</strong><small>{place.address || "地址待补充"}</small><small>{place.opinionCount} 位观点 · {place.visitCount} 次到访 · {place.photoCount} 张照片</small></div><a className="secondary-button" href={`/place/${place.groupPlaceId}`}>查看 / 管理记录</a></li>)}</ul> : <p className="empty-note">没有上架中的地点。</p>}<h3>已下架</h3>{archivedPlaces.length ? <ul className="management-list">{archivedPlaces.map((place) => <li key={place.groupPlaceId}><div><strong>{place.name}</strong><small>{place.archivedByName || "历史处理记录"} · {place.archivedAt ? new Date(place.archivedAt).toLocaleDateString("zh-CN") : ""}</small><small>原因：{place.archivedReason || "历史下架记录未留存原因"}</small></div><RestorePlaceButton id={place.groupPlaceId} /></li>)}</ul> : <p className="empty-note">没有已下架地点。</p>}<h3>去试试候选</h3>{pendingCandidates.length ? <ul className="management-list">{pendingCandidates.map((candidate) => <li key={candidate.id}><div><strong>{candidate.name}</strong><small>仍在等待真实体验。</small></div><a className="secondary-button" href="/try">管理候选</a></li>)}</ul> : <p className="empty-note">没有待处理候选。</p>}{removedCandidates.length ? <ul className="management-list">{removedCandidates.map((candidate) => <li key={candidate.id}><div><strong>{candidate.name}</strong><small>{candidate.resolutionType || "历史处理记录"}{candidate.resolutionReason ? ` · ${candidate.resolutionReason}` : ""}</small></div>{["creator_removed", "manager_removed"].includes(candidate.resolutionType ?? "") ? <RestoreCandidateButton id={candidate.id} /> : <span>不可恢复</span>}</li>)}</ul> : null}<h3>已隐藏内容</h3>{hiddenContent.length ? <ul className="management-list">{hiddenContent.map((item) => <li key={`${item.type}-${item.id}`}><div><strong>{item.placeName} · {item.type === "visit" ? "到访记录" : "照片"}</strong><small>{new Date(item.hiddenAt).toLocaleString("zh-CN")}</small><small>原因：{item.reason}</small></div><RestoreContentButton item={item} /></li>)}</ul> : <p className="empty-note">没有已隐藏内容。</p>}</section>;
}
